### ISSUE TITLE
Add additional information during registration

### ISSUE THREAD

**Issue by aledbf** [progrium/go-extpoints#6]
Is possible to add a "warning" if the extension is not implementing some methods from the interface?
(now just does not register the extension)

**Comment by progrium** [comment]
I'm pretty sure that is the *only* reason it will ever not register. That can be better documented.

**Comment by progrium** [comment]
I guess that's not true. It can return false if it's already been registered. So you think a warning to stderr is appropriate?

**Comment by aledbf** [comment]
> a warning to stderr is appropriate?

That's enough for me :)

**Comment by progrium** [comment]
Well so after looking into it, you _can't_ Register an extension with the wrong type. The only time this is possible is if you use the package level `Register` (now renamed `RegisterExtension`), and in that case it doesn't register if it doesn't have the right type/interface. So there's no way for you to get into a bad state... the only thing is if you use the package level register method you need to know it won't register. But you can find out by looking at the return value... 

So I'm not sure a warning is necessary...

**Comment by aledbf** [comment]
You are right

```
# command-line-arguments
./hello.go:8: cannot use new(HelloComponent) (type *HelloComponent) as type extpoints.Subcommand in argument to subcommands.Register:
    *HelloComponent does not implement extpoints.Subcommand (wrong type for Run method)
        have Run()
        want Run([]string)
```
